app = 'extension-sync-service'
primary_region = 'ams'

[build]
[build.args]
SERVER_URL = 'https://extension-sync-service.fly.dev'
VITE_VAPID_PUBLIC_KEY = 'BMqPDaTMUgZtFkfOlQdan2gbrl4SRxdO2MD6gRTC2yDcRiY60MjILnCapUQjPAm3C0xpUlH-xh1pT_eMJuFHUV4'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0

[[vm]]
memory = '256mb'
cpu_kind = 'shared'
cpus = 1
